# Generated by Django 5.2.17 on 2026-10-01 11:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Generator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='Название')),
                ('motohours', models.FloatField(default=0, verbose_name='Наработка, м/ч')),
                ('last_service_motohours', models.FloatField(default=0, verbose_name='Наработка на последнем ТО')),
            ],
            options={
                'verbose_name': 'дизель-генератор',
                'verbose_name_plural': 'дизель-генераторы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('serial', models.CharField(max_length=50, unique=True, verbose_name='Серийный номер')),
                ('measures', models.CharField(choices=[('air_temp', 'Температура воздуха'), ('humidity', 'Влажность воздуха'), ('wind_speed', 'Скорость ветра'), ('wind_dir', 'Направление ветра'), ('snow_depth', 'Толщина снежного покрова'), ('water_temp', 'Температура морской воды'), ('salinity', 'Солёность морской воды'), ('ice_recon', 'Ледовая разведка')], max_length=20, verbose_name='Измеряет')),
                ('calibration_interval_days', models.PositiveIntegerField(default=180, verbose_name='Интервал калибровки, дн.')),
                ('last_calibration', models.DateField(blank=True, null=True, verbose_name='Последняя калибровка')),
            ],
            options={
                'verbose_name': 'прибор',
                'verbose_name_plural': 'приборы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Название')),
                ('start_date', models.DateField(verbose_name='Начало')),
                ('end_date', models.DateField(verbose_name='Окончание')),
            ],
            options={
                'verbose_name': 'смена',
                'verbose_name_plural': 'смены',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('category', models.CharField(choices=[('fuel', 'Топливо'), ('food', 'Продовольствие'), ('medicine', 'Медикаменты')], max_length=10, verbose_name='Категория')),
                ('unit', models.CharField(max_length=10, verbose_name='Ед. изм.')),
                ('quantity', models.FloatField(default=0, verbose_name='Остаток')),
                ('min_quantity', models.FloatField(verbose_name='Норма (минимум)')),
                ('target_quantity', models.FloatField(verbose_name='Целевой запас')),
            ],
            options={
                'verbose_name': 'позиция склада',
                'verbose_name_plural': 'склад',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('specialty', models.CharField(choices=[('glaciologist', 'Гляциолог'), ('meteorologist', 'Метеоролог'), ('radio_operator', 'Радист'), ('mechanic', 'Механик'), ('doctor', 'Врач')], max_length=20, verbose_name='Специальность')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'сотрудники',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='ExtremeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('storm', 'Шторм'), ('blizzard', 'Пурга'), ('ice_drift', 'Ледовый дрейф')], max_length=12, verbose_name='Характер')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время')),
                ('description', models.TextField(verbose_name='Описание')),
                ('measures_taken', models.TextField(verbose_name='Принятые меры')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'нештатная ситуация',
                'verbose_name_plural': 'журнал нештатных ситуаций',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='CalibrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calibrated_at', models.DateField(verbose_name='Дата')),
                ('passed', models.BooleanField(default=True, verbose_name='Успешно')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Примечание')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibrations', to='station.instrument')),
            ],
            options={
                'verbose_name': 'запись о калибровке',
                'verbose_name_plural': 'журнал калибровок',
                'ordering': ['-calibrated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MotoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.FloatField(verbose_name='Моточасы')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('generator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='station.generator')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('motohours', models.FloatField()),
                ('note', models.CharField(blank=True, max_length=200)),
                ('generator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='station.generator')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delta', models.FloatField(verbose_name='Изменение (− расход, + приход)')),
                ('moved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='station.stockitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-moved_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Количество')),
                ('status', models.CharField(choices=[('pending', 'На утверждении'), ('approved', 'Утверждена'), ('rejected', 'Отклонена'), ('fulfilled', 'Исполнена')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='station.stockitem')),
            ],
            options={
                'verbose_name': 'заявка на снабжение',
                'verbose_name_plural': 'заявки на снабжение',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obs_type', models.CharField(choices=[('air_temp', 'Температура воздуха'), ('humidity', 'Влажность воздуха'), ('wind_speed', 'Скорость ветра'), ('wind_dir', 'Направление ветра'), ('snow_depth', 'Толщина снежного покрова'), ('water_temp', 'Температура морской воды'), ('salinity', 'Солёность морской воды'), ('ice_recon', 'Ледовая разведка')], max_length=20, verbose_name='Вид измерения')),
                ('value', models.FloatField(verbose_name='Значение')),
                ('observed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата и время')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Примечание')),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='station.instrument', verbose_name='Прибор')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Оператор')),
            ],
            options={
                'verbose_name': 'наблюдение',
                'verbose_name_plural': 'наблюдения',
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['obs_type', '-observed_at'], name='station_obs_obs_typ_8f587e_idx')],
            },
        ),
        migrations.CreateModel(
            name='DutySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('part', models.CharField(choices=[('day', 'День (08–20)'), ('night', 'Ночь (20–08)')], max_length=5, verbose_name='Время суток')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='station.employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duties', to='station.shift')),
            ],
            options={
                'verbose_name': 'дежурство',
                'verbose_name_plural': 'график дежурств',
                'ordering': ['date', 'part'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'date', 'part'), name='uniq_duty')],
            },
        ),
        migrations.CreateModel(
            name='ShiftMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification', models.CharField(choices=[('junior', 'Начальный'), ('middle', 'Средний'), ('senior', 'Высокий'), ('expert', 'Эксперт')], max_length=10, verbose_name='Квалификация')),
                ('arrival_date', models.DateField(verbose_name='Дата прибытия')),
                ('health', models.CharField(choices=[('good', 'Здоров'), ('satisfactory', 'Удовлетворительно'), ('limited', 'Ограниченно годен'), ('unfit', 'Не годен к дежурству')], default='good', max_length=15, verbose_name='Состояние здоровья')),
                ('health_note', models.CharField(blank=True, max_length=200, verbose_name='Примечание врача')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='station.employee')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='station.shift')),
            ],
            options={
                'verbose_name': 'участник смены',
                'verbose_name_plural': 'участники смен',
                'constraints': [models.UniqueConstraint(fields=('shift', 'employee'), name='uniq_member')],
            },
        ),
    ]
